### PR TITLE
Update to 1.0.1948 rev787

### PR DESCRIPTION
**Pull request by Sefank**

### CODE REVIEW

**Comment by duduluu** [comment]
Why change the indent whitout content changing?

**Comment by Sefank** [comment]
Not on purpose. The original files changed the indent and I just committed the files that is picked up from the latest game. I think it's better to remain the change of indent for further update issues.

**Comment by duduluu** [comment]
The files in the Keyed directory are not original files, they are resovled by the tool RimTrans, not by manually copying.
The tool would normalize indent in all of the files. (The indent in original files are not unified, I think it's not good.)

**Comment by Sefank** [comment]
Oh sorry for carelessness. So need I rollback the change and recommit it?

**Comment by duduluu** [comment]
No, thx.
I will update by RimTrans after getting home. Thanks for your reminding.
BTW, I'm working in developing the new 3.0 version of RimTrans https://github.com/RimWorld-zh/RimTrans/tree/3.0-alpha
The WIP commit for this repo will be discarded in future. Due to Ludeon change lot of the structure of Defs, the 2.0 RimTrans is outdate.

**Pull request closed without merging**
